api:
  build: .
  command: python3 app.py
  expose:
  - "80"

k6:
  image: loadimpact/k6
  links:
  - api:api
  volumes:
  - ./performance:/tmp/performance
  environment:
  - API_HOST=api
  - API_PORT=80
  command: run /tmp/performance/happy_path_perf.js